---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Posts
- type: directory
  path: site/posts
  label: Posts
  create: all
  match: "**/*"
  exclude: "**/posts.json"
  new_doc_ext: md
  templates:
  - post
- type: directory
  path: site/external-posts
  label: External Posts
  create: all
  match: "**/*"
  exclude: "**/external-posts.json"
  new_doc_ext: md
  templates:
  - external-post
- type: heading
  label: Work
- type: directory
  path: site/publications
  label: Publications
  create: all
  match: "**/*"
  exclude: "**/publications.json"
  new_doc_ext: md
  templates:
  - publication
- type: directory
  path: site/presentations
  label: Presentations
  create: all
  match: "**/*"
  exclude: "**/presentations.json"
  new_doc_ext: md
  templates:
  - presentation
- type: heading
  label: Pages
- type: document
  path: site/_data/about.json
  label: About
- type: document
  path: site/_data/contact.json
  label: Contact
- type: directory
  path: site
  label: Other Pages
  create: all
  match: "*.md"
  new_doc_ext: md
- type: heading
  label: Settings
- type: document
  path: site/_data/site.json
  label: Settings
- type: document
  path: site/_data/navigation.json
  label: Navigation
- type: document
  path: site/_data/socialMedia.json
  label: Social Media Links
upload_dir: site/static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_output_directory: dist
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run start
