---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: site/posts
  label: Posts
  create: all
  match: "**/*"
  exclude: "/site/posts/posts.json"
  new_doc_ext: md
- type: directory
  path: site/external-posts
  label: External Posts
  create: all
  match: "**/*"
  exclude: "/site/posts/external-posts/external-posts.json"
  new_doc_ext: md
- type: directory
  path: site/publications
  label: Publications
  create: all
  match: "**/*"
  exclude: "/site/publications/publications.json"
  new_doc_ext: ".md"
- type: directory
  path: site/presentations
  label: Presentations
  create: all
  match: "**/*"
  exclude: "/site/presentations/presentations.json"
  new_doc_ext: ".md"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
